### ISSUE TITLE
上行测速

### ISSUE THREAD

**Issue by SheYu09** [ljxi/NetworkPanel#17]
大佬，能否在网页上加入上行测速，或者是支持iOS的app

**Comment by ljxi** [comment]
网页端因浏览器限制，上行测速不能得到很好的支持。没有开发iOS APP的计划

**Comment by SheYu09** [comment]
安卓机，我有一台三星的，app安装直接提示“解析包出现问题”

**Comment by SheYu09** [comment]
> 网页端因浏览器限制，上行测速不能得到很好的支持。没有开发iOS APP的计划

安卓机，我有一台三星的，app安装界面直接提示“解析包出现问题”

**Comment by ljxi** [comment]
安卓版本要9以上

**Comment by SheYu09** [comment]
> 安卓版本要9以上
超级尴尬的安卓机，Android 8.机
