### ISSUE TITLE
延迟显示优化

### ISSUE THREAD

**Issue by ZBrettonYe** [ljxi/NetworkPanel#4]
我看后台时访问204页面来获取延迟的。
是否可以参考https://webtest.geetest.com/ 对不同的访问链接显示相应的延迟？底部的延迟参考一口气使用太多来源不是很有意义

**Comment by ljxi** [comment]
底部的延迟显示第一行来自华为的204页面，第二行来自Cloudflare的204页面，用于分别显示国内网络延迟和国际网络延迟，对于其中任意一项的数据都是具有代表性的，你提供的这个网址也使用了相同的原理，只是检查了多个页面分别显示了而已，同类数据太多参考价值不大

**Comment by ZBrettonYe** [comment]
打搅了, 看了一下 js代码，好像的确是这样的。下面的CF的204 标红原来是检查是否能连外网。非常nice
