### ISSUE TITLE
github-pages 无界面

### ISSUE THREAD

**Issue by ymyuuu** [ljxi/NetworkPanel#7]
<img width="516" alt="image" src="https://github.com/ljxi/NetworkPanel/assets/135582157/5b05dc60-c4ca-4243-8202-8a5d7d47e517">

为什么自己github-pages 没有界面呀

**Comment by ljxi** [comment]
检查一下分支设置对了没有，应该配置成gh-pages分支，具体细节查阅Github Pages有关教程
